name: CI/CD Pipeline

on:
  push:
    branches:
      - joseCastro_p1_base

env:
   DOTNET_TOOLS_PATH: ./tools
   NUGET_PATH: ./tools/nuget-packages

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build TrainProject.sln

      - name: Install coverage tools
        run: |
          cd myApp.Tests
          mkdir reports
          dotnet add package coverlet.msbuild --package-directory ../${{ env.NUGET_PATH }}

      - name: Run unit tests with coverage
        run: |
          cd myApp.Tests
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=reports/coverage

      - name: Validate coverage
        run: |
          cd scripts
          pwsh ./validate_coverage.ps1

      - name: Generate HTML coverage report
        run: |
          cd myApp.Tests
          dotnet tool install dotnet-reportgenerator-globaltool --tool-path ../${{ env.DOTNET_TOOLS_PATH }}
          ../${{ env.DOTNET_TOOLS_PATH }}/reportgenerator -reports:reports/coverage.cobertura.xml -targetdir:reports/coveragereport -reporttypes:Html

      - name: Publish app
        run: |
          dotnet publish myApp/myApp.csproj -c Release -o myApp/publish
  
      - name: Log in to the Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PAT | docker login -u $DOCKER_USER --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:dev .

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:dev ${{ secrets.DOCKER_USERNAME }}/myapp:v1.0.0

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:v1.0.0

  deploy-dev:
    needs: ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PAT | docker login -u $DOCKER_USER --password-stdin

      - name: Pull and run image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:v1.0.0
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:v1.0.0